config/routes.rb
Ukulima::Application.routes.draw do
  mount KannelRails::Engine => '/sms'
  root to: 'admin/dashboard#index'

  get 'signup', to: 'admin#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :products
  resources :farmers

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get 'farmers', to: 'users#farmers'
    get 'buyers', to: 'users#buyers'
    match '/message', to: 'dashboard#message', via: [:get, :post]
    resources :users
    resources :admins
  end
end

app/views/admin/shared/_header.html.erb
<!-- 2. $MAIN_NAVIGATION ===========================================================================

	Main navigation
-->
<div id="main-navbar" class="navbar navbar-inverse" role="navigation">
<!-- Main menu toggle -->
<button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>

<div class="navbar-inner">
<!-- Main navbar header -->
<div class="navbar-header">

  <!-- Logo -->
  <a href="<%= root_path %>" class="navbar-brand">
    Ukulima Admin
  </a>

  <!-- Main navbar toggle -->
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

</div> <!-- / .navbar-header -->

<div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
<div>

<div class="right clearfix">
<ul class="nav navbar-nav pull-right right-navbar-nav">


<li class="nav-icon-btn nav-icon-btn-danger dropdown">
  <a href="index.html#notifications" class="dropdown-toggle" data-toggle="dropdown">
    <span class="label">5</span>
    <i class="nav-icon fa fa-bullhorn"></i>
    <span class="small-screen-text">Notifications</span>
  </a>

  <!-- NOTIFICATIONS -->

  <!-- Javascript -->
  <script>
      init.push(function () {
          $('#main-navbar-notifications').slimScroll({ height: 250 });
      });
  </script>
  <!-- / Javascript -->

  <div class="dropdown-menu widget-notifications no-padding" style="width: 300px">
    <div class="notifications-list" id="main-navbar-notifications">

      <div class="notification">
        <div class="notification-title text-danger">SYSTEM</div>
        <div class="notification-description"><strong>Error 500</strong>: Syntax error in index.php at line <strong>461</strong>.</div>
        <div class="notification-ago">12h ago</div>
        <div class="notification-icon fa fa-hdd-o bg-danger"></div>
      </div> <!-- / .notification -->

      <div class="notification">
        <div class="notification-title text-info">STORE</div>
        <div class="notification-description">You have <strong>9</strong> new orders.</div>
        <div class="notification-ago">12h ago</div>
        <div class="notification-icon fa fa-truck bg-info"></div>
      </div> <!-- / .notification -->

      <div class="notification">
        <div class="notification-title text-default">CRON DAEMON</div>
        <div class="notification-description">Job <strong>"Clean DB"</strong> has been completed.</div>
        <div class="notification-ago">12h ago</div>
        <div class="notification-icon fa fa-clock-o bg-default"></div>
      </div> <!-- / .notification -->

      <div class="notification">
        <div class="notification-title text-success">SYSTEM</div>
        <div class="notification-description">Server <strong>up</strong>.</div>
        <div class="notification-ago">12h ago</div>
        <div class="notification-icon fa fa-hdd-o bg-success"></div>
      </div> <!-- / .notification -->

      <div class="notification">
        <div class="notification-title text-warning">SYSTEM</div>
        <div class="notification-description"><strong>Warning</strong>: Processor load <strong>92%</strong>.</div>
        <div class="notification-ago">12h ago</div>
        <div class="notification-icon fa fa-hdd-o bg-warning"></div>
      </div> <!-- / .notification -->

    </div> <!-- / .notifications-list -->
    <a href="index.html#" class="notifications-link">MORE NOTIFICATIONS</a>
  </div> <!-- / .dropdown-menu -->
</li>

<!-- /3. $END_NAVBAR_ICON_BUTTONS -->

<li>
  <form class="navbar-form pull-left">
    <input type="text" class="form-control" placeholder="Search">
  </form>
</li>

<li class="dropdown">
  <a href="index.html#" class="dropdown-toggle user-menu" data-toggle="dropdown">
    <%= image_tag('theareba.jpg') %>
    <span><%= current_user.name %></span>
  </a>
  <ul class="dropdown-menu">
    <li><a href=""><span class="label label-warning pull-right">New</span>Profile</a></li>
    <li><a href=""><span class="badge badge-primary pull-right">New</span>Account</a></li>
    <li><a href=""><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a></li>
    <li class="divider"></li>
    <li><a href="<%= logout_path %>"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
  </ul>
</li>
</ul> <!-- / .navbar-nav -->
</div> <!-- / .right -->
</div>
</div> <!-- / #main-navbar-collapse -->
</div> <!-- / .navbar-inner -->
</div> <!-- / #main-navbar -->
<!-- /2. $END_MAIN_NAVIGATION -->

app/views/admin/shared/_sidebar.html.erb
<!-- 4. $MAIN_MENU ================================================================================= -->
<div id="main-menu" role="navigation">
<div id="main-menu-inner">
<div class="menu-content top" id="menu-content-demo">
  <!-- Menu custom content demo
       CSS:        styles/pixel-admin-less/demo.less or styles/pixel-admin-scss/_demo.scss
       Javascript: html/assets/demo/demo.js
   -->
  <div>
    <div class="text-bg"><span class="text-semibold"><%= current_user.name %></span></div>

    <%= image_tag('theareba.jpg') %>
    <div class="btn-group">
      <a href="" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-envelope"></i></a>
      <a href="" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-user"></i></a>
      <a href="" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-cog"></i></a>
      <a href="<%= logout_path %>" class="btn btn-xs btn-danger btn-outline dark"><i class="fa fa-power-off"></i></a>
    </div>
    <a href="index.html#" class="close">&times;</a>
  </div>
</div>
<ul class="navigation">
  <li>
    <a href="<%= root_path %>"><i class="menu-icon fa fa-dashboard"></i><span class="mm-text">Dashboard</span></a>
  </li>
  <li class="mm-dropdown">
    <a href="<%= "#{root_path}#" %>"><i class="menu-icon fa fa-users"></i><span class="mm-text">Users</span></a>
    <ul>
      <li>
        <a tabindex="-1" href="<%= admin_farmers_path %>"><span class="mm-text">Farmers</span></a>
      </li>
      <li>
        <a tabindex="-1" href="<%= admin_buyers_path %>"><span class="mm-text">Buyers</span></a>
      </li>
    </ul>
  </li>
  <li>
    <a href="<%= admin_message_path %>"><i class="menu-icon fa fa-envelope"></i><span class="mm-text">Message Sendouts</span></a>
  </li>
  <li class="mm-dropdown">
    <a href="index.html#"><i class="menu-icon fa fa-bar-chart-o"></i><span class="mm-text">Reports</span></a>
  </li>
</ul> <!-- / .navigation -->
<div class="menu-content">
  <a href="#" class="btn btn-primary btn-block btn-outline dark">Create Invoice</a>
</div>
</div> <!-- / #main-menu-inner -->
</div> <!-- / #main-menu -->
<!-- /4. $MAIN_MENU -->